### PR TITLE
Update recipe to pick up version 4.0.1

### LINKED ISSUE #15: Package license file
Currently the license file is not being included in Conda packages. Would be good to add `license_file` to `about` with the name of the license file in the source distribution so that it gets packaged.

xref: https://github.com/conda-forge/scons-feedstock/pull/14#issuecomment-599302168

### PR DESCRIPTION
**Pull request by Anthchirp**
pypi project was apparently renamed scons -> SCons, which led to the [auto update bot failing](https://conda-forge.org/status/) with
```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '4.0.1' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz'
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged. (Fixes #15)

### CODE REVIEW

**Comment by Anthchirp** [comment]
Added `license_file` entry. I assume avoiding pip was done on purpose.

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

2.7 builds are expected to fail. Unfortunately, the Windows builds are not.

**Comment by Anthchirp** [comment]
Ready for review :slightly_smiling_face:

**Comment by stuertz** [comment]
Thank you @Anthchirp

**Pull request merged**
